name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  ACR_NAME: mywebapidemoacr4u
  IMAGE_NAME: mywebapi
  WEBAPP_NAME: mywebapi-prod

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME

   # - name: Build Image
      # run: |
      #   docker build \
      #     -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

    - name: Build Image
      run: |
        docker build -t myimage .

    - name: Push Image
      run: |
        docker push \
          $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    - name: Configure Web App Container
      run: |
        az webapp config container set \
          --name $WEBAPP_NAME \
          --resource-group <resource-group> \
          --container-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    - name: Restart Web App
      run: |
        az webapp restart \
          --name $WEBAPP_NAME \
          --resource-group <resource-group>
